- name: Initial Setup
  hosts: web-*
  become: true
  tasks:
    - name: Install system dependencies
      apt: 
        name: 
          - acl
          - git 
          - python3
          - python3-venv 
          - libssl-dev 
          - libffi-dev 
          - build-essential 
          - libpython3-dev 
          - python3-minimal 
          - authbind
          - iptables
        state: present
        update_cache: yes

    - name: Create a user account
      user:
        name: cowrie
        shell: /bin/bash
        state: present

- name: Install and Start Cowrie
  hosts: web-*
  become: true
  vars: 
    workdir: '/opt/cowrie'
  tasks:
    - name: Checkout the code
      #become_user: cowrie
      git:
        repo: 'http://github.com/cowrie/cowrie'
        dest: '{{workdir}}'
        force: yes

    - name: Create Virtual Enviroment
      shell:
        cmd: "python3 -m venv cowrie-env"
        chdir: /opt/
      args:
        creates: "/opt/cowrie-env/bin/python"

    - name: Upgrade Pip
      pip:
        name: pip
        state: latest

    - name: Install Requirements
      pip:
        requirements: "{{workdir}}/requirements.txt"
        virtualenv: /opt/cowrie-env
        state: latest
        
    - name: Install Cowrie config
      template:
        src: ~/ansible/templates/cowrie.cfg.j2
        dest: '{{workdir}}/etc/cowrie.cfg'

    - name: Config Cowrie Service
      copy:
         remote_src: yes
         src: '{{workdir}}/docs/systemd/etc/systemd/system/'
         dest: '/etc/systemd/system'

    - name: Change Directory Permissions
      file: 
        path: '{{item}}'
        owner: cowrie
        recurse: yes
        mode: 
      loop:
        - '/opt/cowrie'
        - 'opt/cowrie-env'

    - name: Start Cowrie Service
      systemd:
         daemon_reload: yes
         name: cowrie.service
         state: restarted
         enabled: yes

    - name: Create IPTables Redirection Rules
      iptables:
         table: nat
         chain: PREROUTING
         protocol: tcp
         destination_port: 22
         jump: REDIRECT
         to_ports: 2222        


# ------------------WORK IN PROGRESS --------------------
# - name: Install and Start Promtail
#   hosts: web-*
#   become: true
#   tasks:
#     - name: Add Grafana key
#       ansible.builtin.apt_key:
#         id: B53AE77BADB630A683046005963FA27710458545
#         url: https://apt.grafana.com/gpg.key
#         state: present

#     - name: Add Grafana Repository
#       apt_repository:
#          repo: 'deb https://apt.grafana.com stable main'
#          update_cache: yes
#          filename: grafana.list

#     - name: Install Promtail
#       apt:
#         name: promtail
#         state: present

#     - name: Install Promtail Config
#       copy:
#         src: templates/promtail.yaml
#         dest: /etc/promtail/config.yml
#         owner: root
#         group: root
#         mode: 0644

#     - name: Restart and Enable Promtail
#       service:
#         name: promtail
#         state: restarted
#         enabled: yes
